import {USER_FIELDS_NAME, USER_TRANSPORT_FIELDS_NAME} from '../constants';
const makeUserData = data => {
  const transport = data[USER_FIELDS_NAME.TRANSPORT][0];
  const newData = {};
  newData[USER_FIELDS_NAME.TRANSPORT] = {
    [USER_TRANSPORT_FIELDS_NAME.ID]: transport[USER_TRANSPORT_FIELDS_NAME.ID]
      ? transport[USER_TRANSPORT_FIELDS_NAME.ID]
      : -1,
    [USER_TRANSPORT_FIELDS_NAME.TRANSPORT_NAME]: transport[
      USER_TRANSPORT_FIELDS_NAME.TRANSPORT_NAME
    ]
      ? transport[USER_TRANSPORT_FIELDS_NAME.TRANSPORT_NAME]
      : '--',
    [USER_TRANSPORT_FIELDS_NAME.NUMBER_PLATE]: transport[
      USER_TRANSPORT_FIELDS_NAME.NUMBER_PLATE
    ]
      ? transport[USER_TRANSPORT_FIELDS_NAME.NUMBER_PLATE]
      : '--',
    [USER_TRANSPORT_FIELDS_NAME.MAKE_MODEL]: transport[
      USER_TRANSPORT_FIELDS_NAME.MAKE_MODEL
    ]
      ? transport[USER_TRANSPORT_FIELDS_NAME.MAKE_MODEL]
      : '--',
    [USER_TRANSPORT_FIELDS_NAME.YEAR]: transport[
      USER_TRANSPORT_FIELDS_NAME.YEAR
    ]
      ? transport[USER_TRANSPORT_FIELDS_NAME.YEAR]
      : '--',
    [USER_TRANSPORT_FIELDS_NAME.COLOR]: transport[
      USER_TRANSPORT_FIELDS_NAME.COLOR
    ]
      ? transport[USER_TRANSPORT_FIELDS_NAME.COLOR]
      : '--',
    [USER_TRANSPORT_FIELDS_NAME.TRANSPORT_ID]: transport[
      USER_TRANSPORT_FIELDS_NAME.TRANSPORT_ID
    ]
      ? transport[USER_TRANSPORT_FIELDS_NAME.TRANSPORT_ID]
      : -1,
    [USER_TRANSPORT_FIELDS_NAME.DRIVER]: transport[
      USER_TRANSPORT_FIELDS_NAME.DRIVER
    ]
      ? transport[USER_TRANSPORT_FIELDS_NAME.DRIVER]
      : -1,
  };
  newData[USER_FIELDS_NAME.CREATED_AT] = data[USER_FIELDS_NAME.CREATED_AT]
    ? data[USER_FIELDS_NAME.CREATED_AT]
    : '2020-07-24T21:51:36.745Z';
  newData[USER_FIELDS_NAME.UPDATED_AT] = data[USER_FIELDS_NAME.UPDATED_AT]
    ? data[USER_FIELDS_NAME.UPDATED_AT]
    : '2020-07-24T21:51:36.745Z';
  newData[USER_FIELDS_NAME.ID] = data[USER_FIELDS_NAME.ID]
    ? data[USER_FIELDS_NAME.ID]
    : 777;
  newData[USER_FIELDS_NAME.SHOW_CHANGE_PASSWORD] = data[
    USER_FIELDS_NAME.SHOW_CHANGE_PASSWORD
  ]
    ? data[USER_FIELDS_NAME.SHOW_CHANGE_PASSWORD]
    : false;
  newData[USER_FIELDS_NAME.NAME] = data[USER_FIELDS_NAME.NAME]
    ? data[USER_FIELDS_NAME.NAME]
    : 'Temp Name';
  newData[USER_FIELDS_NAME.PHONE] = data[USER_FIELDS_NAME.PHONE]
    ? data[USER_FIELDS_NAME.PHONE]
    : '090078601';
  newData[USER_FIELDS_NAME.EMAIL] = data[USER_FIELDS_NAME.EMAIL]
    ? data[USER_FIELDS_NAME.EMAIL]
    : '--';
  newData[USER_FIELDS_NAME.ADDRESS] = data[USER_FIELDS_NAME.ADDRESS]
    ? data[USER_FIELDS_NAME.ADDRESS]
    : '--';
  newData[USER_FIELDS_NAME.CITY] = data[USER_FIELDS_NAME.CITY]
    ? data[USER_FIELDS_NAME.CITY]
    : '--';
  newData[USER_FIELDS_NAME.TOWN] = data[USER_FIELDS_NAME.TOWN]
    ? data[USER_FIELDS_NAME.TOWN]
    : '';
  newData[USER_FIELDS_NAME.POST_CODE] = data[USER_FIELDS_NAME.POST_CODE]
    ? data[USER_FIELDS_NAME.POST_CODE]
    : '--';
  newData[USER_FIELDS_NAME.STATUS] = data[USER_FIELDS_NAME.STATUS]
    ? data[USER_FIELDS_NAME.STATUS]
    : '--';

  newData[USER_FIELDS_NAME.IS_ONLINE] =
    data[USER_FIELDS_NAME.STATUS] == 'ACTIVE' ? true : false;

  newData[USER_FIELDS_NAME.CAPACITY] = data[USER_FIELDS_NAME.CAPACITY]
    ? data[USER_FIELDS_NAME.CAPACITY] === 'NaN'
      ? 0
      : data[USER_FIELDS_NAME.CAPACITY]
    : 0;
  newData[USER_FIELDS_NAME.IMAGE] = data[USER_FIELDS_NAME.IMAGE]
    ? data[USER_FIELDS_NAME.IMAGE]
    : '';
  newData[USER_FIELDS_NAME.LOCATION] = data[USER_FIELDS_NAME.LOCATION]
    ? data[USER_FIELDS_NAME.LOCATION]
    : {};
  newData[USER_FIELDS_NAME.USER] = data[USER_FIELDS_NAME.USER]
    ? data[USER_FIELDS_NAME.USER]
    : {};
  newData[USER_FIELDS_NAME.BUSINESS] = data[USER_FIELDS_NAME.BUSINESS]
    ? data[USER_FIELDS_NAME.BUSINESS]
    : {};
  newData[USER_FIELDS_NAME.REFRESH_TOKEN] = data[USER_FIELDS_NAME.REFRESH_TOKEN]
    ? data[USER_FIELDS_NAME.REFRESH_TOKEN]
    : '';
  newData[USER_FIELDS_NAME.ROUTE_STARTED] = data[USER_FIELDS_NAME.ROUTE_STARTED]
    ? data[USER_FIELDS_NAME.ROUTE_STARTED]
    : false;
  return newData;
};
export {makeUserData};
